
logging:
    level:
        tk.mybatis: info
        com.appogg.website: info
        com.appogg.website.mapper: debug

spring:
    application:
        name: appogg
    jackson:
        date-format: yyyy-MM-dd HH:mm
        time-zone: GMT+8
        default-property-inclusion: non_null
    profiles:
        active: prod
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/appoggdata?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: root

server:
    port: 8999

mybatis:
    basepackage: com.appogg.website.mapper
    xmlLocation: classpath:mapper/**/*.xml
    mapper-locations: "classpath*:mapper/*.xml"

#redis-cache 相关
#redis:
#  cluster:
#    nodes: 127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005
#    # 服务或应用名
#  sysName: appogg
#  enable: true
#  database: 0